theme: jekyll-theme-cayman
exclude: README.md
webmaster_verifications:
  google: 5CrG7Z0xNEQCt0N-GzrRvOZlRBZ8ztC9XiI1bNA8q38
github:
  is_project_page: false
title: Delta-Sigma
tagline: Digital Urdu Resources
description: We collect resources needed for users of Urdu and other Nastaliq-based language in the digital world. This is Urdu-focused but hopefully some will also be useful to users of other. Hoping to add links to dictionaries, articles, setting up fonts etc.
author: Danyal Saeed
